#!/bin/bash
# Script made to install all Auris Controller and folders for Music_for_deaf project.

cd ~/

echo "Creating MUSIC_DEAF folder"
mkdir -p MUSIC_DEAF

echo "Creating MUSIC_DEAF subfolders"
cd MUSIC_DEAF/
mkdir -p music_for_deaf/{auris-core/,auris-drivers/}
mkdir -p music_for_deaf_files/{audios/,auris_melodies/,midis/}

echo "Cloning repositories from GIT-LAB"
cd music_for_deaf/
git clone git@gitlab.lavid.ufpb.br:auris/auris-controller.git
git clone git@gitlab.lavid.ufpb.br:auris/auris-scripts.git

cd auris-core/
git clone git@gitlab.lavid.ufpb.br:auris/midi-melody-generator.git
git clone git@gitlab.lavid.ufpb.br:auris/auris-stream.git
git clone git@gitlab.lavid.ufpb.br:auris/auris-filter.git

cd ..
cd auris-drivers/
git clone git@gitlab.lavid.ufpb.br:auris/auris-bracelet.git

echo "Installing all dependencies"
cd ~/MUSIC_DEAF/music_for_deaf/auris-scripts
./setupScript
