#!/bin/bash
# Script made to install all dependecies to use Midi-Melody for Music_for_deaf project.

echo "Installing FFMPEG"
sudo add-apt-repository ppa:mc3man/trusty-media
sudo apt-get update
sudo apt-get install ffmpeg -y
echo "##################################################"

echo "Installing numpy e scipy"
sudo apt-get install python-numpy python-scipy -y
echo "##################################################"

echo "Installing Libs"
sudo apt-get install libboost-filesystem-dev -y
sudo apt-get install libpstreams-dev -y
sudo apt-get install libfreetype6-dev -y
echo "##################################################"

echo "Installing Python-PIP"
sudo apt-get install python-pip -y
pip install --upgrade pip
echo "##################################################"

echo "Installing PIP dependencies"
sudo pip install wheel
echo "##################################################"
sudo pip install cython==0.19.2
echo "##################################################"
sudo apt-get install python-pandas -y
echo "##################################################"
sudo pip install functools32
echo "##################################################"
sudo pip install --upgrade setuptools
echo "##################################################"
sudo pip install Distribute
echo "##################################################"
echo "Installing Librosa"
sudo pip install librosa==0.4.0
echo "##################################################"
sudo pip install scikits.samplerate
echo "##################################################"

echo "Installing Vamp-Examples"
cd Files/vamp-1.1.0
sudo python setup.py install
sudo apt-get install vamp-examples -y
echo "##################################################"

echo "Copying Melodia Lib"
cd ..
cd MTG-MELODIA\ 1.0
sudo cp mtg-melodia.cat /usr/lib/vamp/
sudo cp mtg-melodia.n3 /usr/lib/vamp/
sudo cp mtg-melodia.so /usr/lib/vamp/
sudo cp README_linux64.txt /usr/lib/vamp/
sudo cp MELODIA\ -\ License.txt /usr/lib/vamp/
echo "##################################################"

cd ..
cd libsamplerate-0.1.8
./configure
make
sudo make install
echo "##################################################"

echo "Installing MIDIUtil"
cd ..
cd MIDIUtil-0.89
sudo python setup.py install
echo "##################################################"

echo "Installing Jams"
cd ..
cd jams-master
sudo python setup.py install
echo "##################################################"

echo "Installing Flask"
sudo pip install flask
echo "##################################################"

#echo "Installing Puredata - BE SURE YOU ARE USING UBUNTU 14.04LTS or less version."
#sudo add-apt-repository ppa:eighthave/pd-extended
#sudo apt-get update
#sudo apt-get install pd-extended
#cd ..
#cd ..
#cd ..
#cd auris-core/auris-filter/Auris_PD
#make
cd ..
cd ..
sudo chmod 755 puredata.sh
echo "##################################################"

echo "Running Midi-Melody Controller"
cd ..
cd ..
cd ..
cd auris-controller
make install
make
echo "#################################################"