#!/bin/bash
# Script made to install all Auris Controller and folders for Music_for_deaf project.

cd ..
echo "Creating MUSIC_DEAF folder"
mkdir -p MUSIC_DEAF
echo "##################################################"

echo "Creating MUSIC_DEAF subfolders"
cd MUSIC_DEAF/
mkdir -p music_for_deaf/{auris-core/,auris-drivers/}
mkdir -p music_for_deaf_files/{audios/,auris_melodies/,midis/,audios_filtered/}
echo "##################################################"

echo "Cloning repositories from GIT-LAB"
cd music_for_deaf/
git clone git@github.com:auris-project/auris-controller.git || git pull origin master
git clone git@github.com:auris-project/auris-scripts.git || git pull origin master
git clone git@github.com:auris-project/auris-server.git || git pull origin master
cd auris-server/
git clone git@github.com:auris-project/auris-front.git || git pull origin master
echo "##################################################"
cd ..
cd auris-core/
git clone git@github.com:auris-project/midi-melody-generator.git || git pull origin master
git clone git@github.com:auris-project/auris-stream.git || git pull origin master
git clone git@github.com:auris-project/auris-filter.git || git pull origin master
echo "##################################################"
cd ..
cd auris-drivers/
git clone git@github.com:auris-project/auris-bracelet.git || git pull origin master
echo "##################################################"

echo "Installing all dependencies"
cd ..
cd auris-scripts/
sudo chmod 755 dependencies_Setup
./dependencies_Setup

echo "Installing essentia"
cd ..
cd auris-scripts
sudo chmod 755 script_essentia.sh
./script_essentia.sh
cd ..
cd auris-core/auris-filter/Auris_Essentia/
make
